version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_go_api
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
        - "5432:5432"
    restart: always
    volumes:
        - db_go_api:/var/lib/postgresql/data
volumes:
  db_go_api: